import json
import os

notebook_json = {
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Lab 03: Benchmark-Aligned Multi-Classifier Email Spam Classification\n",
    "**Course:** MDI3003 - Advanced Predictive Analytics  \n",
    "**Faculty:** Dr. Durgesh Kumar  \n",
    "**Student Name:** Geetha Priya S  \n",
    "**Registration No:** 23MID0021  \n",
    "**Github Repository:** https://github.com/GEETHA1137/Advanced_predictive_analytics_lab.git  \n",
    "\n",
    "---\n",
    "\n",
    "### Educational Boundary Disclaimer\n",
    "> **Boundary:** This laboratory exercise is designed for educational and predictive modeling research. The classifiers and draft generation scripts are prototypes and must not be connected to a live email-send server, mailbox scraper, or external service containing confidential PII without institutional clearance.\n",
    "\n",
    "---\n",
    "\n",
    "### Project Framing\n",
    "- **Target Population:** Incoming team inbox email traffic.\n",
    "- **Outcome:** Spam vs. Legitimate/Ham status classification.\n",
    "- **Positive Class:** Spam (1 = Spam, 0 = Legitimate).\n",
    "- **Key Objective:** Compare TF-IDF Naive Bayes, TF-IDF KNN, and pre-trained embedding (GloVe) PyTorch BiLSTM classifiers on the locked test set.\n",
    "- **Success Criteria:** Maximize accuracy and ROC-AUC on the locked test set, while maintaining low False Positives to avoid routing legitimate mail to spam.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 1. Environment Setup & Library Imports\n",
    "import os\n",
    "import sys\n",
    "import re\n",
    "import urllib.request\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "\n",
    "from sklearn.model_selection import train_test_split, StratifiedKFold, GridSearchCV\n",
    "from sklearn.feature_extraction.text import TfidfVectorizer\n",
    "from sklearn.naive_bayes import MultinomialNB\n",
    "from sklearn.neighbors import KNeighborsClassifier\n",
    "from sklearn.metrics import (\n",
    "    accuracy_score, precision_score, recall_score, f1_score, roc_auc_score,\n",
    "    confusion_matrix, classification_report, roc_curve\n",
    ")\n",
    "\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "import torch.optim as optim\n",
    "from torch.utils.data import DataLoader, TensorDataset\n",
    "\n",
    "RANDOM_STATE = 42\n",
    "np.random.seed(RANDOM_STATE)\n",
    "torch.manual_seed(RANDOM_STATE)\n",
    "\n",
    "# Check device\n",
    "device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')\n",
    "print(f\"Device: {device}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 2. Load Dataset using Local Tools\n",
    "sys.path.append(os.getcwd())\n",
    "import tools\n",
    "\n",
    "print(\"Loading dataset...\")\n",
    "df = tools.load_data()\n",
    "df = tools.clean_corpus(df)\n",
    "\n",
    "print(f\"Cleaned dataset size: {df.shape}\")\n",
    "print(\"Class counts (0 = Ham, 1 = Spam):\")\n",
    "print(df['label'].value_counts())\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 3. Stratified Train-Test Split (80:20)\n",
    "df_train, df_test = train_test_split(\n",
    "    df, test_size=0.20, stratify=df['label'], random_state=RANDOM_STATE\n",
    ")\n",
    "\n",
    "X_train_text = df_train['text_cleaned'].values\n",
    "y_train = df_train['label'].values\n",
    "X_test_text = df_test['text_cleaned'].values\n",
    "y_test = df_test['label'].values\n",
    "\n",
    "print(f\"Train size: {len(df_train)}\")\n",
    "print(f\"Test size: {len(df_test)}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 4. Feature Extraction using TF-IDF\n",
    "vectorizer = TfidfVectorizer(\n",
    "    lowercase=True,\n",
    "    strip_accents='unicode',\n",
    "    ngram_range=(1, 2),\n",
    "    min_df=2,\n",
    "    max_df=0.98,\n",
    "    sublinear_tf=True,\n",
    "    max_features=20000\n",
    ")\n",
    "\n",
    "X_train_tfidf = vectorizer.fit_transform(X_train_text)\n",
    "X_test_tfidf = vectorizer.transform(X_test_text)\n",
    "print(f\"TF-IDF feature dimensions: {X_train_tfidf.shape}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 5. Naive Bayes (MultinomialNB) Tuning & Fit\n",
    "nb_param_grid = {'alpha': [0.01, 0.1, 0.5, 1.0, 2.0, 5.0]}\n",
    "nb_clf = MultinomialNB()\n",
    "cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)\n",
    "\n",
    "nb_grid = GridSearchCV(nb_clf, nb_param_grid, cv=cv, scoring='f1_macro', n_jobs=-1)\n",
    "nb_grid.fit(X_train_tfidf, y_train)\n",
    "\n",
    "best_nb = nb_grid.best_estimator_\n",
    "print(f\"Best MNB params: {nb_grid.best_params_}\")\n",
    "print(f\"5-Fold CV Macro F1: {nb_grid.best_score_:.4f}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 6. KNN Classifier Tuning & Fit\n",
    "knn_param_grid = {'n_neighbors': [3, 5, 7, 11, 15], 'weights': ['uniform', 'distance']}\n",
    "knn_clf = KNeighborsClassifier()\n",
    "\n",
    "knn_grid = GridSearchCV(knn_clf, knn_param_grid, cv=cv, scoring='f1_macro', n_jobs=-1)\n",
    "knn_grid.fit(X_train_tfidf, y_train)\n",
    "\n",
    "best_knn = knn_grid.best_estimator_\n",
    "print(f\"Best KNN params: {knn_grid.best_params_}\")\n",
    "print(f\"5-Fold CV Macro F1: {knn_grid.best_score_:.4f}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": None,
   "metadata": {},
   "outputs": [],
   "source": [
    "# 7. Sequence Preparation & GloVe Download\n",
    "glove_path = \"glove.6B.50d.txt\"\n",
    "if not os.path.exists(glove_path):\n",
    "    url = \"https://huggingface.co/JeremiahZ/glove/resolve/main/glove.6B.50d.txt\"\n",
    "    print(f\"Downloading GloVe vectors...\")\n",
    "    urllib.request.urlretrieve(url, glove_path)\n",
    "    print(\"Download finished!\")\n",
    "\n",
    "# Simple Tokenizer\n",
    "class CustomTokenizer:\n",
    "    def __init__(self, max_vocab=20000, oov_token=\"<OOV>\"):\n",
    "        self.max_vocab = max_vocab\n",
    "        self.oov_token = oov_token\n",
    "        self.word_index = {}\n",
    "        self.index_word = {}\n",
    "\n",
    "    def fit_on_texts(self, texts):\n",
    "        from collections import Counter\n",
    "        word_counts = Counter()\n",
    "        for text in texts:\n",
    "            words = re.findall(r'\\b\\w+\\b', str(text).lower())\n",
    "            word_counts.update(words)\n",
    "        \n",
    "        most_common = word_counts.most_common(self.max_vocab - 2)\n",
    "        self.word_index = {self.oov_token: 1}\n",
    "        for i, (word, _) in enumerate(most_common):\n",
    "            self.word_index[word] = i + 2\n",
    "        self.index_word = {v: k for k, v in self.word_index.items()}\n",
    "\n",
    "    def texts_to_sequences(self, texts):\n",
    "        sequences = []\n",
    "        for text in texts:\n",
    "            words = re.findall(r'\\b\\w+\\b', str(text).lower())\n",
    "            seq = [self.word_index.get(w, 1) for w in words]\n",
    "            sequences.append(seq)\n",
    "        return sequences\n",
    "\n",
    "def pad_sequences(sequences, maxlen=200):\n",
    "    padded = []\n",
    "    for seq in sequences:\n",
    "        if len(seq) > maxlen:\n",
    "            padded.append(seq[:maxlen])\n",
    "        else:\n",
    "            padded.append(seq + [0] * (maxlen - len(seq)))\n",
    "    return np.array(padded)\n",
    "\n",
    "tokenizer = CustomTokenizer(max_vocab=20000)\n",
    "tokenizer.fit_on_texts(X_train_text)\n",
    "\n",
    "X_train_pad = pad_sequences(tokenizer.texts_to_sequences(X_train_text), maxlen=200)\n",
    "X_test_pad = pad_sequences(tokenizer.texts_to_sequences(X_test_text), maxlen=200)\n",
    "\n",
    "# Load embedding weights\n",
    "EMBED_DIM = 50\n",
    "vocab_size = len(tokenizer.word_index) + 1\n",
    "embedding_matrix = np.zeros((vocab_size, EMBED_DIM))\n",
    "glove_vectors = {}\n",
    "with open(glove_path, 'r', encoding='utf-8') as f:\n",
    "    for line in f:\n",
    "        parts = line.strip().split()\n",
    "        if len(parts) == EMBED_DIM + 1:\n",
    "            glove_vectors[parts[0]] = np.asarray(parts[1:], dtype='float32')\n",
    "\n",
    "for word, i in tokenizer.word_index.items():\n",
    "    if word in glove_vectors:\n",
    "        embedding_matrix[i] = glove_vectors[word]\n",
    "    else:\n",
    "        embedding_matrix[i] = np.random.normal(scale=0.6, size=(EMBED_DIM,))\n"
   ]
  },
  {
   "cell_type": "code",
   "metadata": {},
   "outputs": [],
   "source": [
    "# 8. Build PyTorch BiLSTM Architecture\n",
    "class PyTorchLSTM(nn.Module):\n",
    "    def __init__(self, vocab_size, embedding_dim, embedding_matrix, hidden_dim=64, output_dim=1, dropout=0.3):\n",
    "        super().__init__()\n",
    "        self.embedding = nn.Embedding(vocab_size, embedding_dim, padding_idx=0)\n",
    "        self.embedding.weight.data.copy_(torch.from_numpy(embedding_matrix))\n",
    "        self.embedding.weight.requires_grad = True\n",
    "        self.lstm = nn.LSTM(embedding_dim, hidden_dim, num_layers=1, bidirectional=True, batch_first=True)\n",
    "        self.fc = nn.Linear(hidden_dim * 2, output_dim)\n",
    "        self.dropout = nn.Dropout(dropout)\n",
    "        \n",
    "    def forward(self, text):\n",
    "        embedded = self.dropout(self.embedding(text))\n",
    "        outputs, _ = self.lstm(embedded)\n",
    "        pooled = torch.mean(outputs, dim=1)\n",
    "        return self.fc(self.dropout(pooled)).squeeze(1)\n"
   ]
  },
  {
   "cell_type": "code",
   "metadata": {},
   "outputs": [],
   "source": [
    "# 9. Train LSTM with Validation & Early Stopping\n",
    "X_tr_dl, X_val_dl, y_tr_dl, y_val_dl = train_test_split(\n",
    "    X_train_pad, y_train, test_size=0.20, stratify=y_train, random_state=42\n",
    ")\n",
    "train_dataset = TensorDataset(torch.tensor(X_tr_dl, dtype=torch.long), torch.tensor(y_tr_dl, dtype=torch.float32))\n",
    "val_dataset = TensorDataset(torch.tensor(X_val_dl, dtype=torch.long), torch.tensor(y_val_dl, dtype=torch.float32))\n",
    "train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)\n",
    "val_loader = DataLoader(val_dataset, batch_size=64, shuffle=False)\n",
    "\n",
    "model = PyTorchLSTM(vocab_size, EMBED_DIM, embedding_matrix).to(device)\n",
    "criterion = nn.BCEWithLogitsLoss().to(device)\n",
    "optimizer = optim.Adam(model.parameters(), lr=1e-3)\n",
    "\n",
    "best_val_loss = float('inf')\n",
    "patience, counter = 3, 0\n",
    "\n",
    "for epoch in range(15):\n",
    "    model.train()\n",
    "    for bx, by in train_loader:\n",
    "        bx, by = bx.to(device), by.to(device)\n",
    "        optimizer.zero_grad()\n",
    "        loss = criterion(model(bx), by)\n",
    "        loss.backward()\n",
    "        optimizer.step()\n",
    "        \n",
    "    model.eval()\n",
    "    val_loss = 0.0\n",
    "    with torch.no_grad():\n",
    "        for bx, by in val_loader:\n",
    "            bx, by = bx.to(device), by.to(device)\n",
    "            val_loss += criterion(model(bx), by).item() * bx.size(0)\n",
    "    val_loss /= len(val_loader.dataset)\n",
    "    print(f\"Epoch {epoch+1} | Val Loss: {val_loss:.4f}\")\n",
    "    \n",
    "    if val_loss < best_val_loss:\n",
    "        best_val_loss = val_loss\n",
    "        torch.save(model.state_dict(), \"best_model_nb.pt\")\n",
    "        counter = 0\n",
    "    else:\n",
    "        counter += 1\n",
    "        if counter >= patience:\n",
    "            print(\"Early stopping!\")\n",
    "            break\n",
    "\n",
    "model.load_state_dict(torch.load(\"best_model_nb.pt\"))\n"
   ]
  },
  {
   "cell_type": "code",
   "metadata": {},
   "outputs": [],
   "source": [
    "# 10. Locked Test Set Evaluation\n",
    "# NB evaluation\n",
    "pred_nb = best_nb.predict(X_test_tfidf)\n",
    "prob_nb = best_nb.predict_proba(X_test_tfidf)[:, 1]\n",
    "\n",
    "# KNN evaluation\n",
    "pred_knn = best_knn.predict(X_test_tfidf)\n",
    "prob_knn = best_knn.predict_proba(X_test_tfidf)[:, 1]\n",
    "\n",
    "# LSTM evaluation\n",
    "model.eval()\n",
    "test_dataset = TensorDataset(torch.tensor(X_test_pad, dtype=torch.long))\n",
    "test_loader = DataLoader(test_dataset, batch_size=64, shuffle=False)\n",
    "prob_lstm = []\n",
    "with torch.no_grad():\n",
    "    for (bx,) in test_loader:\n",
    "        prob_lstm.extend(torch.sigmoid(model(bx.to(device))).cpu().numpy())\n",
    "prob_lstm = np.array(prob_lstm)\n",
    "pred_lstm = (prob_lstm >= 0.5).astype(int)\n",
    "\n",
    "# Functions to extract metrics\n",
    "def print_results(name, y_true, y_pred, y_prob):\n",
    "    print(f\"=== {name} locked test metrics ===\")\n",
    "    print(classification_report(y_true, y_pred))\n",
    "    print(f\"ROC-AUC: {roc_auc_score(y_true, y_prob):.4f}\\n\")\n",
    "\n",
    "print_results(\"Naive Bayes\", y_test, pred_nb, prob_nb)\n",
    "print_results(\"KNN\", y_test, pred_knn, prob_knn)\n",
    "print_results(\"BiLSTM (GloVe)\", y_test, pred_lstm, prob_lstm)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}

notebook_path = "23MID0021_Lab03_EmailAI.ipynb"
with open(notebook_path, 'w', encoding='utf-8') as f:
    json.dump(notebook_json, f, indent=1)
print("Jupyter Notebook created at:", notebook_path)
